export const voiceProfilesData = [
  {
    Voice: 'Riya',
    language: 'Multi(language)',
    stt: 'speechmatics',
    llm: 'openai',
    TTS: 'PlayHT',
    vad: 'TRUE',
    name: 'Riya(Multilingual)',
    gender: 'F',
    quality: 'Good',
    estimated_cost: 8,
    instructions: 'High/Normal',
    description:
      'Multilingual female voice with balanced clarity and fluency. Ideal for global applications requiring diverse language support.',
  },
  {
    Voice: 'Priya',
    language: 'Multi(language)',
    stt: 'speechmatics',
    llm: 'openai',
    TTS: 'PlayHT',
    vad: 'TRUE',
    name: 'Priya(Multilingual)',
    gender: 'F',
    quality: 'Good',
    estimated_cost: 8,
    instructions: 'High/Normal',
    description:
      'Versatile multilingual voice offering clear and friendly communication, suitable for customer support and e-learning.',
  },
  {
    Voice: 'Rahul',
    language: 'English',
    stt: 'speechmatics',
    llm: 'openai',
    TTS: 'PlayHT',
    vad: 'TRUE',
    name: 'Rahul(Multilingual)',
    gender: 'M',
    quality: 'Good',
    estimated_cost: 8,
    instructions: 'High/Normal',
    description:
      'English male voice with natural tone and pacing. Suitable for formal dialogues and informative content.',
  },
  {
    Voice: 'Riya',
    language: 'Multi(language)',
    stt: 'speechmatics',
    llm: 'openai',
    TTS: 'PlayHT',
    vad: 'TRUE',
    name: 'Riya(Multilingual)',
    gender: 'F',
    quality: 'Good',
    estimated_cost: 7,
    instructions: 'High/Normal',
    description:
      'Cost-effective version of Riya with reliable multilingual delivery. Great for casual or internal use-cases.',
  },
  {
    Voice: 'Riya',
    language: 'Multi(language)',
    stt: 'speechmatics',
    llm: 'openai',
    TTS: 'PlayHT',
    vad: 'TRUE',
    name: 'Riya(Multilingual)',
    gender: 'F',
    quality: 'High',
    estimated_cost: 12,
    instructions: 'High/Normal',
    description:
      'Premium high-quality variant of Riya with enhanced audio clarity and expressive tone. Ideal for premium AI agents.',
  },
  {
    Voice: 'Asha',
    language: 'Hindi, English',
    stt: 'speechmatics',
    llm: 'openai',
    TTS: 'PlayHT',
    vad: 'TRUE',
    name: 'Asha(Bilingual)',
    gender: 'F',
    quality: 'Good',
    estimated_cost: 9,
    instructions: 'High/Normal',
    description:
      'Bilingual female voice fluent in Hindi and English, best suited for regional applications and user-friendly interfaces.',
  },
];
