#!/usr/bin/env python3
"""
Generate Django migration files for database indexing strategy.
Run this script to create all migration files for Phase 1 (Critical) indexes.

Usage: python create_index_migrations.py
"""

import os
from pathlib import Path

# Migration templates for each app
MIGRATIONS = {
    'users': {
        'file': 'add_critical_indexes_users.py',
        'content': '''# Generated by indexing strategy 2026-01-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221101_1748'),
    ]

    operations = [
        # Add db_index to User.user_token (max_length=20 as per model)
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.CharField(verbose_name='User Token', max_length=20, blank=True, null=True, db_index=True),
        ),
        # Add db_index to User.referrer_code
        migrations.AlterField(
            model_name='user',
            name='referrer_code',
            field=models.CharField(verbose_name='Referrer Code', max_length=20, blank=True, null=True, db_index=True),
        ),
        # Add db_index to BlackListToken.token (TextField in model)
        migrations.AlterField(
            model_name='blacklisttoken',
            name='token',
            field=models.TextField(verbose_name='Token', null=True, blank=True, db_index=True),
        ),
        # Add db_index to BlackListToken.user_id (IntegerField, not ForeignKey)
        migrations.AlterField(
            model_name='blacklisttoken',
            name='user_id',
            field=models.IntegerField(null=True, blank=True, db_index=True),
        ),
        # Add db_index to UserDevice.is_active
        migrations.AlterField(
            model_name='userdevice',
            name='is_active',
            field=models.BooleanField(default=True, db_index=True, help_text='Disable to stop sending push notifications'),
        ),
    ]
'''
    },

    'space': {
        'file': 'add_critical_indexes_space.py',
        'content': '''# Generated by indexing strategy 2026-01-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Assumes models already exist in database
    ]

    operations = [
        # OrganizationMemberRoles indexes
        migrations.AlterField(
            model_name='organizationmemberroles',
            name='is_active',
            field=models.BooleanField(default=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='organizationmemberroles',
            index=models.Index(fields=['organization', 'is_active'], name='space_orgmem_org_act_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmemberroles',
            index=models.Index(fields=['user', 'is_active'], name='space_orgmem_usr_act_idx'),
        ),

        # SpaceMemberRoles indexes
        migrations.AddIndex(
            model_name='spacememberroles',
            index=models.Index(fields=['space', 'user'], name='space_spcmem_spc_usr_idx'),
        ),

        # SpaceInvite indexes (max_length=40 as per model)
        migrations.AlterField(
            model_name='spaceinvite',
            name='invite_token',
            field=models.CharField(max_length=40, blank=True, null=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='spaceinvite',
            name='user_email',
            field=models.EmailField(blank=True, null=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='spaceinvite',
            index=models.Index(fields=['user_email', 'invite_verified'], name='space_inv_email_ver_idx'),
        ),

        # OrganizationInvite indexes (max_length=40 as per model)
        migrations.AlterField(
            model_name='organizationinvite',
            name='invite_token',
            field=models.CharField(max_length=40, blank=True, null=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='user_email',
            field=models.EmailField(blank=True, null=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='organizationinvite',
            index=models.Index(fields=['user_email', 'invite_verified'], name='space_orginv_email_ver_idx'),
        ),

        # SpaceOrganizationBillingInfo indexes
        migrations.AlterField(
            model_name='spaceorganizationbillinginfo',
            name='default',
            field=models.BooleanField(default=False, db_index=True),
        ),
        migrations.AddIndex(
            model_name='spaceorganizationbillinginfo',
            index=models.Index(fields=['organization', 'default'], name='space_bill_org_def_idx'),
        ),
    ]
'''
    },

    'thread': {
        'file': 'add_critical_indexes_thread.py',
        'content': '''# Generated by indexing strategy 2026-01-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Assumes models already exist in database
    ]

    operations = [
        # ThreadPost field indexes (max_length=99 as per model)
        migrations.AlterField(
            model_name='threadpost',
            name='post_status',
            field=models.CharField(max_length=99, db_index=True),
        ),
        migrations.AlterField(
            model_name='threadpost',
            name='privacy_type',
            field=models.CharField(max_length=99, db_index=True),
        ),
        migrations.AlterField(
            model_name='threadpost',
            name='is_live',
            field=models.BooleanField(default=False, db_index=True),
        ),
        # live_id is IntegerField, not CharField
        migrations.AlterField(
            model_name='threadpost',
            name='live_id',
            field=models.IntegerField(blank=True, null=True, db_index=True),
        ),

        # ThreadPost composite indexes
        migrations.AddIndex(
            model_name='threadpost',
            index=models.Index(fields=['space', 'post_status'], name='thread_post_spc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='threadpost',
            index=models.Index(fields=['space', 'is_live'], name='thread_post_spc_live_idx'),
        ),
        migrations.AddIndex(
            model_name='threadpost',
            index=models.Index(fields=['user', 'post_status'], name='thread_post_usr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='threadpost',
            index=models.Index(fields=['main_post', 'post_status'], name='thread_post_main_status_idx'),
        ),

        # ThreadPostReaction indexes
        migrations.AddIndex(
            model_name='threadpostreaction',
            index=models.Index(fields=['post', 'reaction_type'], name='thread_react_post_type_idx'),
        ),
        migrations.AddIndex(
            model_name='threadpostreaction',
            index=models.Index(fields=['user', 'post'], name='thread_react_usr_post_idx'),
        ),

        # ThreadPostPermission indexes
        migrations.AddIndex(
            model_name='threadpostpermission',
            index=models.Index(fields=['post', 'user'], name='thread_perm_post_usr_idx'),
        ),
    ]
'''
    },

    'metrics': {
        'file': 'add_critical_indexes_metrics.py',
        'content': '''# Generated by indexing strategy 2026-01-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Assumes models already exist in database
    ]

    operations = [
        # CallLog composite indexes - CRITICAL for performance
        # Note: Individual fields already have db_index=True in model
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['organization', 'product_id'], name='metrics_call_org_prod_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['bridge', 'call_status'], name='metrics_call_brg_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['organization', 'creation_time'], name='metrics_call_org_time_idx'),
        ),

        # Metrics composite indexes
        migrations.AddIndex(
            model_name='metrics',
            index=models.Index(fields=['organization', 'product_id'], name='metrics_met_org_prod_idx'),
        ),
    ]
'''
    },

    'subscription': {
        'file': 'add_critical_indexes_subscription.py',
        'content': '''# Generated by indexing strategy 2026-01-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Assumes models already exist in database
    ]

    operations = [
        # ActiveSubscription indexes - CRITICAL for billing
        migrations.AlterField(
            model_name='activesubscription',
            name='is_active',
            field=models.BooleanField(default=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activesubscription',
            name='expired',
            field=models.BooleanField(default=False, db_index=True),
        ),
        migrations.AddIndex(
            model_name='activesubscription',
            index=models.Index(fields=['organization', 'is_active'], name='sub_actsub_org_act_idx'),
        ),
        migrations.AddIndex(
            model_name='activesubscription',
            index=models.Index(fields=['is_active', 'expired'], name='sub_actsub_act_exp_idx'),
        ),

        # SubscriptionInvoice indexes
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='status',
            field=models.CharField(max_length=50, db_index=True),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['organization', 'status'], name='sub_invoice_org_stat_idx'),
        ),
    ]
'''
    },
}


def create_migrations():
    """Create migration files in respective app directories."""
    project_root = Path(__file__).parent

    print("=" * 70)
    print("CREATING DATABASE INDEX MIGRATIONS (CORRECTED)")
    print("=" * 70)
    print()

    for app_name, migration_data in MIGRATIONS.items():
        app_path = project_root / 'unpod' / app_name / 'migrations'

        if not app_path.exists():
            print(f"⚠️  Warning: {app_path} does not exist, skipping {app_name}")
            continue

        migration_file = app_path / migration_data['file']

        # Write migration file
        with open(migration_file, 'w') as f:
            f.write(migration_data['content'])

        print(f"✅ Created: {migration_file}")

    print()
    print("=" * 70)
    print("CORRECTIONS MADE:")
    print("=" * 70)
    print()
    print("✓ Users: Fixed user_token max_length (20 not 255)")
    print("✓ Users: Fixed BlackListToken.token to TextField")
    print("✓ Users: Fixed BlackListToken to use user_id (IntegerField)")
    print("✓ Space: Fixed invite_token max_length (40 not 255)")
    print("✓ Thread: Fixed post_status max_length (99 not 20)")
    print("✓ Thread: Fixed privacy_type max_length (99 not 20)")
    print("✓ Thread: Fixed live_id to IntegerField (not CharField)")
    print()
    print("=" * 70)
    print("NEXT STEPS:")
    print("=" * 70)
    print()
    print("1. Test on QA:")
    print("   export DJANGO_SETTINGS_MODULE=config.settings.qa")
    print("   python manage.py migrate users")
    print("   python manage.py migrate space")
    print("   python manage.py migrate thread")
    print("   python manage.py migrate metrics")
    print("   python manage.py migrate subscription")
    print()
    print("2. Verify indexes created:")
    print("   python manage.py dbshell")
    print("   \\di+ *_idx  # PostgreSQL")
    print()
    print("3. Run performance comparison:")
    print("   python analyze_query_performance.py --environment qa")
    print()


if __name__ == "__main__":
    create_migrations()
