export type CountryCode = {
  code: string;
  short: string;
  flag: string;
  name: string;
};

export const countryCodes: CountryCode[] = [
  { code: '+93', short: 'AF', flag: '🇦🇫', name: 'Afghanistan' },
  { code: '+355', short: 'AL', flag: '🇦🇱', name: 'Albania' },
  { code: '+213', short: 'DZ', flag: '🇩🇿', name: 'Algeria' },
  { code: '+376', short: 'AD', flag: '🇦🇩', name: 'Andorra' },
  { code: '+244', short: 'AO', flag: '🇦🇴', name: 'Angola' },
  { code: '+54', short: 'AR', flag: '🇦🇷', name: 'Argentina' },
  { code: '+374', short: 'AM', flag: '🇦🇲', name: 'Armenia' },
  { code: '+61', short: 'AU', flag: '🇦🇺', name: 'Australia' },
  { code: '+43', short: 'AT', flag: '🇦🇹', name: 'Austria' },
  { code: '+994', short: 'AZ', flag: '🇦🇿', name: 'Azerbaijan' },
  { code: '+1242', short: 'BS', flag: '🇧🇸', name: 'Bahamas' },
  { code: '+973', short: 'BH', flag: '🇧🇭', name: 'Bahrain' },
  { code: '+880', short: 'BD', flag: '🇧🇩', name: 'Bangladesh' },
  { code: '+1246', short: 'BB', flag: '🇧🇧', name: 'Barbados' },
  { code: '+375', short: 'BY', flag: '🇧🇾', name: 'Belarus' },
  { code: '+32', short: 'BE', flag: '🇧🇪', name: 'Belgium' },
  { code: '+501', short: 'BZ', flag: '🇧🇿', name: 'Belize' },
  { code: '+229', short: 'BJ', flag: '🇧🇯', name: 'Benin' },
  { code: '+975', short: 'BT', flag: '🇧🇹', name: 'Bhutan' },
  { code: '+591', short: 'BO', flag: '🇧🇴', name: 'Bolivia' },
  { code: '+387', short: 'BA', flag: '🇧🇦', name: 'Bosnia and Herzegovina' },
  { code: '+267', short: 'BW', flag: '🇧🇼', name: 'Botswana' },
  { code: '+55', short: 'BR', flag: '🇧🇷', name: 'Brazil' },
  { code: '+673', short: 'BN', flag: '🇧🇳', name: 'Brunei' },
  { code: '+359', short: 'BG', flag: '🇧🇬', name: 'Bulgaria' },
  { code: '+226', short: 'BF', flag: '🇧🇫', name: 'Burkina Faso' },
  { code: '+257', short: 'BI', flag: '🇧🇮', name: 'Burundi' },
  { code: '+855', short: 'KH', flag: '🇰🇭', name: 'Cambodia' },
  { code: '+237', short: 'CM', flag: '🇨🇲', name: 'Cameroon' },
  { code: '+1', short: 'CA', flag: '🇨🇦', name: 'Canada' },
  { code: '+238', short: 'CV', flag: '🇨🇻', name: 'Cabo Verde' },
  { code: '+236', short: 'CF', flag: '🇨🇫', name: 'Central African Republic' },
  { code: '+235', short: 'TD', flag: '🇹🇩', name: 'Chad' },
  { code: '+56', short: 'CL', flag: '🇨🇱', name: 'Chile' },
  { code: '+86', short: 'CN', flag: '🇨🇳', name: 'China' },
  { code: '+57', short: 'CO', flag: '🇨🇴', name: 'Colombia' },
  { code: '+269', short: 'KM', flag: '🇰🇲', name: 'Comoros' },
  { code: '+242', short: 'CG', flag: '🇨🇬', name: 'Congo' },
  { code: '+243', short: 'CD', flag: '🇨🇩', name: 'Congo (DRC)' },
  { code: '+506', short: 'CR', flag: '🇨🇷', name: 'Costa Rica' },
  { code: '+225', short: 'CI', flag: '🇨🇮', name: "Côte d'Ivoire" },
  { code: '+385', short: 'HR', flag: '🇭🇷', name: 'Croatia' },
  { code: '+53', short: 'CU', flag: '🇨🇺', name: 'Cuba' },
  { code: '+357', short: 'CY', flag: '🇨🇾', name: 'Cyprus' },
  { code: '+420', short: 'CZ', flag: '🇨🇿', name: 'Czech Republic' },
  { code: '+45', short: 'DK', flag: '🇩🇰', name: 'Denmark' },
  { code: '+253', short: 'DJ', flag: '🇩🇯', name: 'Djibouti' },
  { code: '+1767', short: 'DM', flag: '🇩🇲', name: 'Dominica' },
  { code: '+1809', short: 'DO', flag: '🇩🇴', name: 'Dominican Republic' },
  { code: '+593', short: 'EC', flag: '🇪🇨', name: 'Ecuador' },
  { code: '+20', short: 'EG', flag: '🇪🇬', name: 'Egypt' },
  { code: '+503', short: 'SV', flag: '🇸🇻', name: 'El Salvador' },
  { code: '+240', short: 'GQ', flag: '🇬🇶', name: 'Equatorial Guinea' },
  { code: '+291', short: 'ER', flag: '🇪🇷', name: 'Eritrea' },
  { code: '+372', short: 'EE', flag: '🇪🇪', name: 'Estonia' },
  { code: '+251', short: 'ET', flag: '🇪🇹', name: 'Ethiopia' },
  { code: '+500', short: 'FK', flag: '🇫🇰', name: 'Falkland Islands' },
  { code: '+679', short: 'FJ', flag: '🇫🇯', name: 'Fiji' },
  { code: '+358', short: 'FI', flag: '🇫🇮', name: 'Finland' },
  { code: '+33', short: 'FR', flag: '🇫🇷', name: 'France' },
  { code: '+241', short: 'GA', flag: '🇬🇦', name: 'Gabon' },
  { code: '+220', short: 'GM', flag: '🇬🇲', name: 'Gambia' },
  { code: '+995', short: 'GE', flag: '🇬🇪', name: 'Georgia' },
  { code: '+49', short: 'DE', flag: '🇩🇪', name: 'Germany' },
  { code: '+233', short: 'GH', flag: '🇬🇭', name: 'Ghana' },
  { code: '+30', short: 'GR', flag: '🇬🇷', name: 'Greece' },
  { code: '+299', short: 'GL', flag: '🇬🇱', name: 'Greenland' },
  { code: '+1473', short: 'GD', flag: '🇬🇩', name: 'Grenada' },
  { code: '+502', short: 'GT', flag: '🇬🇹', name: 'Guatemala' },
  { code: '+224', short: 'GN', flag: '🇬🇳', name: 'Guinea' },
  { code: '+245', short: 'GW', flag: '🇬🇼', name: 'Guinea-Bissau' },
  { code: '+592', short: 'GY', flag: '🇬🇾', name: 'Guyana' },
  { code: '+509', short: 'HT', flag: '🇭🇹', name: 'Haiti' },
  { code: '+504', short: 'HN', flag: '🇭🇳', name: 'Honduras' },
  { code: '+852', short: 'HK', flag: '🇭🇰', name: 'Hong Kong' },
  { code: '+36', short: 'HU', flag: '🇭🇺', name: 'Hungary' },
  { code: '+354', short: 'IS', flag: '🇮🇸', name: 'Iceland' },
  { code: '+91', short: 'IN', flag: '🇮🇳', name: 'India' },
  { code: '+62', short: 'ID', flag: '🇮🇩', name: 'Indonesia' },
  { code: '+98', short: 'IR', flag: '🇮🇷', name: 'Iran' },
  { code: '+964', short: 'IQ', flag: '🇮🇶', name: 'Iraq' },
  { code: '+353', short: 'IE', flag: '🇮🇪', name: 'Ireland' },
  { code: '+972', short: 'IL', flag: '🇮🇱', name: 'Israel' },
  { code: '+39', short: 'IT', flag: '🇮🇹', name: 'Italy' },
  { code: '+1876', short: 'JM', flag: '🇯🇲', name: 'Jamaica' },
  { code: '+81', short: 'JP', flag: '🇯🇵', name: 'Japan' },
  { code: '+962', short: 'JO', flag: '🇯🇴', name: 'Jordan' },
  { code: '+7', short: 'KZ', flag: '🇰🇿', name: 'Kazakhstan' },
  { code: '+254', short: 'KE', flag: '🇰🇪', name: 'Kenya' },
  { code: '+686', short: 'KI', flag: '🇰🇮', name: 'Kiribati' },
  { code: '+383', short: 'XK', flag: '🇽🇰', name: 'Kosovo' },
  { code: '+965', short: 'KW', flag: '🇰🇼', name: 'Kuwait' },
  { code: '+996', short: 'KG', flag: '🇰🇬', name: 'Kyrgyzstan' },
  { code: '+856', short: 'LA', flag: '🇱🇦', name: 'Laos' },
  { code: '+371', short: 'LV', flag: '🇱🇻', name: 'Latvia' },
  { code: '+961', short: 'LB', flag: '🇱🇧', name: 'Lebanon' },
  { code: '+266', short: 'LS', flag: '🇱🇸', name: 'Lesotho' },
  { code: '+231', short: 'LR', flag: '🇱🇷', name: 'Liberia' },
  { code: '+218', short: 'LY', flag: '🇱🇾', name: 'Libya' },
  { code: '+423', short: 'LI', flag: '🇱🇮', name: 'Liechtenstein' },
  { code: '+370', short: 'LT', flag: '🇱🇹', name: 'Lithuania' },
  { code: '+352', short: 'LU', flag: '🇱🇺', name: 'Luxembourg' },
  { code: '+853', short: 'MO', flag: '🇲🇴', name: 'Macao' },
  { code: '+261', short: 'MG', flag: '🇲🇬', name: 'Madagascar' },
  { code: '+265', short: 'MW', flag: '🇲🇼', name: 'Malawi' },
  { code: '+60', short: 'MY', flag: '🇲🇾', name: 'Malaysia' },
  { code: '+960', short: 'MV', flag: '🇲🇻', name: 'Maldives' },
  { code: '+223', short: 'ML', flag: '🇲🇱', name: 'Mali' },
  { code: '+356', short: 'MT', flag: '🇲🇹', name: 'Malta' },
  { code: '+692', short: 'MH', flag: '🇲🇭', name: 'Marshall Islands' },
  { code: '+222', short: 'MR', flag: '🇲🇷', name: 'Mauritania' },
  { code: '+230', short: 'MU', flag: '🇲🇺', name: 'Mauritius' },
  { code: '+52', short: 'MX', flag: '🇲🇽', name: 'Mexico' },
  { code: '+691', short: 'FM', flag: '🇫🇲', name: 'Micronesia' },
  { code: '+373', short: 'MD', flag: '🇲🇩', name: 'Moldova' },
  { code: '+377', short: 'MC', flag: '🇲🇨', name: 'Monaco' },
  { code: '+976', short: 'MN', flag: '🇲🇳', name: 'Mongolia' },
  { code: '+382', short: 'ME', flag: '🇲🇪', name: 'Montenegro' },
  { code: '+212', short: 'MA', flag: '🇲🇦', name: 'Morocco' },
  { code: '+258', short: 'MZ', flag: '🇲🇿', name: 'Mozambique' },
  { code: '+95', short: 'MM', flag: '🇲🇲', name: 'Myanmar' },
  { code: '+264', short: 'NA', flag: '🇳🇦', name: 'Namibia' },
  { code: '+674', short: 'NR', flag: '🇳🇷', name: 'Nauru' },
  { code: '+977', short: 'NP', flag: '🇳🇵', name: 'Nepal' },
  { code: '+31', short: 'NL', flag: '🇳🇱', name: 'Netherlands' },
  { code: '+64', short: 'NZ', flag: '🇳🇿', name: 'New Zealand' },
  { code: '+505', short: 'NI', flag: '🇳🇮', name: 'Nicaragua' },
  { code: '+227', short: 'NE', flag: '🇳🇪', name: 'Niger' },
  { code: '+234', short: 'NG', flag: '🇳🇬', name: 'Nigeria' },
  { code: '+850', short: 'KP', flag: '🇰🇵', name: 'North Korea' },
  { code: '+389', short: 'MK', flag: '🇲🇰', name: 'North Macedonia' },
  { code: '+47', short: 'NO', flag: '🇳🇴', name: 'Norway' },
  { code: '+968', short: 'OM', flag: '🇴🇲', name: 'Oman' },
  { code: '+92', short: 'PK', flag: '🇵🇰', name: 'Pakistan' },
  { code: '+680', short: 'PW', flag: '🇵🇼', name: 'Palau' },
  { code: '+507', short: 'PA', flag: '🇵🇦', name: 'Panama' },
  { code: '+675', short: 'PG', flag: '🇵🇬', name: 'Papua New Guinea' },
  { code: '+595', short: 'PY', flag: '🇵🇾', name: 'Paraguay' },
  { code: '+51', short: 'PE', flag: '🇵🇪', name: 'Peru' },
  { code: '+63', short: 'PH', flag: '🇵🇭', name: 'Philippines' },
  { code: '+48', short: 'PL', flag: '🇵🇱', name: 'Poland' },
  { code: '+351', short: 'PT', flag: '🇵🇹', name: 'Portugal' },
  { code: '+1787', short: 'PR', flag: '🇵🇷', name: 'Puerto Rico' },
  { code: '+974', short: 'QA', flag: '🇶🇦', name: 'Qatar' },
  { code: '+40', short: 'RO', flag: '🇷🇴', name: 'Romania' },
  { code: '+7', short: 'RU', flag: '🇷🇺', name: 'Russia' },
  { code: '+250', short: 'RW', flag: '🇷🇼', name: 'Rwanda' },
  { code: '+1869', short: 'KN', flag: '🇰🇳', name: 'Saint Kitts and Nevis' },
  { code: '+1758', short: 'LC', flag: '🇱🇨', name: 'Saint Lucia' },
  { code: '+508', short: 'PM', flag: '🇵🇲', name: 'Saint Pierre and Miquelon' },
  {
    code: '+1784',
    short: 'VC',
    flag: '🇻🇨',
    name: 'Saint Vincent and the Grenadines',
  },
  { code: '+685', short: 'WS', flag: '🇼🇸', name: 'Samoa' },
  { code: '+378', short: 'SM', flag: '🇸🇲', name: 'San Marino' },
  { code: '+239', short: 'ST', flag: '🇸🇹', name: 'Sao Tome and Principe' },
  { code: '+966', short: 'SA', flag: '🇸🇦', name: 'Saudi Arabia' },
  { code: '+221', short: 'SN', flag: '🇸🇳', name: 'Senegal' },
  { code: '+381', short: 'RS', flag: '🇷🇸', name: 'Serbia' },
  { code: '+248', short: 'SC', flag: '🇸🇨', name: 'Seychelles' },
  { code: '+232', short: 'SL', flag: '🇸🇱', name: 'Sierra Leone' },
  { code: '+65', short: 'SG', flag: '🇸🇬', name: 'Singapore' },
  { code: '+421', short: 'SK', flag: '🇸🇰', name: 'Slovakia' },
  { code: '+386', short: 'SI', flag: '🇸🇮', name: 'Slovenia' },
  { code: '+677', short: 'SB', flag: '🇸🇧', name: 'Solomon Islands' },
  { code: '+252', short: 'SO', flag: '🇸🇴', name: 'Somalia' },
  { code: '+27', short: 'ZA', flag: '🇿🇦', name: 'South Africa' },
  { code: '+82', short: 'KR', flag: '🇰🇷', name: 'South Korea' },
  { code: '+211', short: 'SS', flag: '🇸🇸', name: 'South Sudan' },
  { code: '+34', short: 'ES', flag: '🇪🇸', name: 'Spain' },
  { code: '+94', short: 'LK', flag: '🇱🇰', name: 'Sri Lanka' },
  { code: '+249', short: 'SD', flag: '🇸🇩', name: 'Sudan' },
  { code: '+597', short: 'SR', flag: '🇸🇷', name: 'Suriname' },
  { code: '+47', short: 'SJ', flag: '🇸🇯', name: 'Svalbard and Jan Mayen' },
  { code: '+46', short: 'SE', flag: '🇸🇪', name: 'Sweden' },
  { code: '+41', short: 'CH', flag: '🇨🇭', name: 'Switzerland' },
  { code: '+963', short: 'SY', flag: '🇸🇾', name: 'Syria' },
  { code: '+886', short: 'TW', flag: '🇹🇼', name: 'Taiwan' },
  { code: '+992', short: 'TJ', flag: '🇹🇯', name: 'Tajikistan' },
  { code: '+255', short: 'TZ', flag: '🇹🇿', name: 'Tanzania' },
  { code: '+66', short: 'TH', flag: '🇹🇭', name: 'Thailand' },
  { code: '+228', short: 'TG', flag: '🇹🇬', name: 'Togo' },
  { code: '+676', short: 'TO', flag: '🇹🇴', name: 'Tonga' },
  { code: '+1868', short: 'TT', flag: '🇹🇹', name: 'Trinidad and Tobago' },
  { code: '+216', short: 'TN', flag: '🇹🇳', name: 'Tunisia' },
  { code: '+90', short: 'TR', flag: '🇹🇷', name: 'Turkey' },
  { code: '+993', short: 'TM', flag: '🇹🇲', name: 'Turkmenistan' },
  { code: '+688', short: 'TV', flag: '🇹🇻', name: 'Tuvalu' },
  { code: '+256', short: 'UG', flag: '🇺🇬', name: 'Uganda' },
  { code: '+380', short: 'UA', flag: '🇺🇦', name: 'Ukraine' },
  { code: '+971', short: 'AE', flag: '🇦🇪', name: 'United Arab Emirates' },
  { code: '+44', short: 'GB', flag: '🇬🇧', name: 'United Kingdom' },
  { code: '+1', short: 'US', flag: '🇺🇸', name: 'United States' },
  { code: '+598', short: 'UY', flag: '🇺🇾', name: 'Uruguay' },
  { code: '+998', short: 'UZ', flag: '🇺🇿', name: 'Uzbekistan' },
  { code: '+678', short: 'VU', flag: '🇻🇺', name: 'Vanuatu' },
  { code: '+379', short: 'VA', flag: '🇻🇦', name: 'Vatican City' },
  { code: '+58', short: 'VE', flag: '🇻🇪', name: 'Venezuela' },
  { code: '+84', short: 'VN', flag: '🇻🇳', name: 'Vietnam' },
  { code: '+967', short: 'YE', flag: '🇾🇪', name: 'Yemen' },
  { code: '+260', short: 'ZM', flag: '🇿🇲', name: 'Zambia' },
  { code: '+263', short: 'ZW', flag: '🇿🇼', name: 'Zimbabwe' },
];

export type RegionOption = {
  label: string;
  value: string;
};

export const regionOptions: RegionOption[] = [
  { label: 'India', value: 'IN' },
  { label: 'US (North America)', value: 'US' },
  { label: 'United Arab Emirates - UAE', value: 'EU' },
];
