export type TaxIdData = {
  country: string;
  countryCode: string;
  flag: string;
  taxIdName: string;
  regex: string;};

export const taxIdData: TaxIdData[] = [
  {
    country: 'Afghanistan',
    countryCode: 'AF',
    flag: '🇦🇫',
    taxIdName: 'TIN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Albania',
    countryCode: 'AL',
    flag: '🇦🇱',
    taxIdName: 'NIPT / TIN',
    regex: '^[A-Z]\\d{8}[A-Z]$',
  },
  {
    country: 'Algeria',
    countryCode: 'DZ',
    flag: '🇩🇿',
    taxIdName: 'NIF',
    regex: '^\\d{15}(\\d{0,5})?$',
  },
  {
    country: 'Argentina',
    countryCode: 'AR',
    flag: '🇦🇷',
    taxIdName: 'CUIT',
    regex: '^\\d{2}-\\d{8}-\\d{1}$',
  },
  {
    country: 'Armenia',
    countryCode: 'AM',
    flag: '🇦🇲',
    taxIdName: 'TIN',
    regex: '^\\d{8}$',
  },
  {
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    taxIdName: 'TFN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Austria',
    countryCode: 'AT',
    flag: '🇦🇹',
    taxIdName: 'UID',
    regex: '^ATU\\d{8}$',
  },
  {
    country: 'Bangladesh',
    countryCode: 'BD',
    flag: '🇧🇩',
    taxIdName: 'BIN / TIN',
    regex: '^\\d{11,15}$',
  },
  {
    country: 'Belarus',
    countryCode: 'BY',
    flag: '🇧🇾',
    taxIdName: 'TIN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Belgium',
    countryCode: 'BE',
    flag: '🇧🇪',
    taxIdName: 'BTW/VAT',
    regex: '^BE0?\\d{9}$',
  },
  {
    country: 'Belize',
    countryCode: 'BZ',
    flag: '🇧🇿',
    taxIdName: 'TIN',
    regex: '^\\d{9,12}$',
  },
  {
    country: 'Bolivia',
    countryCode: 'BO',
    flag: '🇧🇴',
    taxIdName: 'TIN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Botswana',
    countryCode: 'BW',
    flag: '🇧🇼',
    taxIdName: 'TIN',
    regex: '^\\d{10}$',
  },
  {
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    taxIdName: 'CPF',
    regex: '^\\d{11}$',
  },
  {
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    taxIdName: 'CNPJ',
    regex: '^\\d{14}$',
  },
  {
    country: 'Cambodia',
    countryCode: 'KH',
    flag: '🇰🇭',
    taxIdName: 'TIN',
    regex: '^\\d{9,12}$',
  },
  {
    country: 'Cameroon',
    countryCode: 'CM',
    flag: '🇨🇲',
    taxIdName: 'TIN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    taxIdName: 'SIN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Chile',
    countryCode: 'CL',
    flag: '🇨🇱',
    taxIdName: 'RUT',
    regex: '^\\d{7,8}-[\\dKk]$',
  },
  {
    country: 'China',
    countryCode: 'CN',
    flag: '🇨🇳',
    taxIdName: 'USCC',
    regex: '^[0-9A-Z]{18}$',
  },
  {
    country: 'Colombia',
    countryCode: 'CO',
    flag: '🇨🇴',
    taxIdName: 'NIT',
    regex: '^\\d{6,10}$',
  },
  {
    country: 'Croatia',
    countryCode: 'HR',
    flag: '🇭🇷',
    taxIdName: 'OIB',
    regex: '^\\d{11}$',
  },
  {
    country: 'Czechia',
    countryCode: 'CZ',
    flag: '🇨🇿',
    taxIdName: 'DIČ / IČO',
    regex: '^\\d{8,10}$',
  },
  {
    country: 'Denmark',
    countryCode: 'DK',
    flag: '🇩🇰',
    taxIdName: 'CVR',
    regex: '^\\d{8}$',
  },
  {
    country: 'Dominican Republic',
    countryCode: 'DO',
    flag: '🇩🇴',
    taxIdName: 'RNC / NRC',
    regex: '^\\d{9}$',
  },
  {
    country: 'Ecuador',
    countryCode: 'EC',
    flag: '🇪🇨',
    taxIdName: 'RUC',
    regex: '^\\d{13}$',
  },
  {
    country: 'Egypt',
    countryCode: 'EG',
    flag: '🇪🇬',
    taxIdName: 'Tax ID',
    regex: '^\\d{9}$',
  },
  {
    country: 'Estonia',
    countryCode: 'EE',
    flag: '🇪🇪',
    taxIdName: 'Isikukood / KMKR',
    regex: '^\\d{11}$',
  },
  {
    country: 'Ethiopia',
    countryCode: 'ET',
    flag: '🇪🇹',
    taxIdName: 'TIN',
    regex: '^\\d{10}$',
  },
  {
    country: 'Finland',
    countryCode: 'FI',
    flag: '🇫🇮',
    taxIdName: 'Y-tunnus',
    regex: '^\\d{7}-\\d$',
  },
  {
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    taxIdName: 'SIREN',
    regex: '^\\d{9}$',
  },
  {
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    taxIdName: 'SIRET',
    regex: '^\\d{14}$',
  },
  {
    country: 'Georgia',
    countryCode: 'GE',
    flag: '🇬🇪',
    taxIdName: 'TIN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    taxIdName: 'Steuer-ID',
    regex: '^\\d{11}$',
  },
  {
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    taxIdName: 'USt-IdNr',
    regex: '^DE\\d{9}$',
  },
  {
    country: 'Greece',
    countryCode: 'GR',
    flag: '🇬🇷',
    taxIdName: 'AFM',
    regex: '^\\d{9}$',
  },
  {
    country: 'Hong Kong',
    countryCode: 'HK',
    flag: '🇭🇰',
    taxIdName: 'BRN',
    regex: '^\\d{8}$',
  },
  {
    country: 'Hungary',
    countryCode: 'HU',
    flag: '🇭🇺',
    taxIdName: 'Adóazonosító',
    regex: '^\\d{10}$',
  },
  {
    country: 'Iceland',
    countryCode: 'IS',
    flag: '🇮🇸',
    taxIdName: 'Kennitala',
    regex: '^\\d{6}[-]?\\d{4}$',
  },
  {
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    taxIdName: 'PAN',
    regex: '^[A-Z]{5}\\d{4}[A-Z]$',
  },
  {
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    taxIdName: 'GSTIN',
    regex: '^\\d{2}[A-Z0-9]{10}\\d[A-Z]\\d$',
  },
  {
    country: 'Indonesia',
    countryCode: 'ID',
    flag: '🇮🇩',
    taxIdName: 'NPWP',
    regex: '^\\d{15}$',
  },
  {
    country: 'Ireland',
    countryCode: 'IE',
    flag: '🇮🇪',
    taxIdName: 'PPSN',
    regex: '^\\d{7}[A-Z]{1,2}$',
  },
  {
    country: 'Israel',
    countryCode: 'IL',
    flag: '🇮🇱',
    taxIdName: 'Mispar Zehut',
    regex: '^\\d{9}$',
  },
  {
    country: 'Italy',
    countryCode: 'IT',
    flag: '🇮🇹',
    taxIdName: 'Codice Fiscale',
    regex: '^[A-Z0-9]{16}$',
  },
  {
    country: 'Italy',
    countryCode: 'IT',
    flag: '🇮🇹',
    taxIdName: 'Partita IVA',
    regex: '^\\d{11}$',
  },
  {
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    taxIdName: 'My Number',
    regex: '^\\d{12}$',
  },
  {
    country: 'Jordan',
    countryCode: 'JO',
    flag: '🇯🇴',
    taxIdName: 'TIN',
    regex: '^\\d{10}$',
  },
  {
    country: 'Kazakhstan',
    countryCode: 'KZ',
    flag: '🇰🇿',
    taxIdName: 'BIN / IIN',
    regex: '^\\d{12}$',
  },
  {
    country: 'Kenya',
    countryCode: 'KE',
    flag: '🇰🇪',
    taxIdName: 'PIN',
    regex: '^[A-Z]{2}\\d{7}[A-Z]$',
  },
  {
    country: 'Kuwait',
    countryCode: 'KW',
    flag: '🇰🇼',
    taxIdName: 'Civil ID / CR',
    regex: '^\\d{12}$',
  },
  {
    country: 'Kyrgyzstan',
    countryCode: 'KG',
    flag: '🇰🇬',
    taxIdName: 'TIN',
    regex: '^\\d{14}$',
  },
  {
    country: 'Latvia',
    countryCode: 'LV',
    flag: '🇱🇻',
    taxIdName: 'PVN / TIN',
    regex: '^LV\\d{11}$',
  },
  {
    country: 'Lebanon',
    countryCode: 'LB',
    flag: '🇱🇧',
    taxIdName: 'TIN',
    regex: '^\\d{8}$',
  },
  {
    country: 'Lithuania',
    countryCode: 'LT',
    flag: '🇱🇹',
    taxIdName: 'PVM / TIN',
    regex: '^LT(\\d{9}|\\d{12})$',
  },
  {
    country: 'Luxembourg',
    countryCode: 'LU',
    flag: '🇱🇺',
    taxIdName: 'TVA',
    regex: '^LU\\d{8}$',
  },
  {
    country: 'Madagascar',
    countryCode: 'MG',
    flag: '🇲🇬',
    taxIdName: 'TIN',
    regex: '^\\d{13}$',
  },
  {
    country: 'Maldives',
    countryCode: 'MV',
    flag: '🇲🇻',
    taxIdName: 'TIN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Malaysia',
    countryCode: 'MY',
    flag: '🇲🇾',
    taxIdName: 'NRIC',
    regex: '^\\d{12}$',
  },
  {
    country: 'Malta',
    countryCode: 'MT',
    flag: '🇲🇹',
    taxIdName: 'VAT',
    regex: '^MT\\d{8}$',
  },
  {
    country: 'Mexico',
    countryCode: 'MX',
    flag: '🇲🇽',
    taxIdName: 'RFC',
    regex: '^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$',
  },
  {
    country: 'Moldova',
    countryCode: 'MD',
    flag: '🇲🇩',
    taxIdName: 'TIN',
    regex: '^\\d{13}$',
  },
  {
    country: 'Monaco',
    countryCode: 'MC',
    flag: '🇲🇨',
    taxIdName: 'TIN',
    regex: '^\\d{10,12}$',
  },
  {
    country: 'Mongolia',
    countryCode: 'MN',
    flag: '🇲🇳',
    taxIdName: 'TIN',
    regex: '^\\d{10}$',
  },
  {
    country: 'Morocco',
    countryCode: 'MA',
    flag: '🇲🇦',
    taxIdName: 'Identifiant Fiscal',
    regex: '^\\d{9}$',
  },
  {
    country: 'Mozambique',
    countryCode: 'MZ',
    flag: '🇲🇿',
    taxIdName: 'NIF',
    regex: '^\\d{9}$',
  },
  {
    country: 'Namibia',
    countryCode: 'NA',
    flag: '🇳🇦',
    taxIdName: 'TIN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Nepal',
    countryCode: 'NP',
    flag: '🇳🇵',
    taxIdName: 'PAN',
    regex: '^\\d{10}$',
  },
  {
    country: 'Netherlands',
    countryCode: 'NL',
    flag: '🇳🇱',
    taxIdName: 'BSN',
    regex: '^\\d{8,9}$',
  },
  {
    country: 'New Zealand',
    countryCode: 'NZ',
    flag: '🇳🇿',
    taxIdName: 'IRD',
    regex: '^\\d{8,9}$',
  },
  {
    country: 'Nigeria',
    countryCode: 'NG',
    flag: '🇳🇬',
    taxIdName: 'TIN',
    regex: '^\\d{9,10}$',
  },
  {
    country: 'Norway',
    countryCode: 'NO',
    flag: '🇳🇴',
    taxIdName: 'Org Number',
    regex: '^\\d{9}$',
  },
  {
    country: 'Oman',
    countryCode: 'OM',
    flag: '🇴🇲',
    taxIdName: 'TRN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Pakistan',
    countryCode: 'PK',
    flag: '🇵🇰',
    taxIdName: 'CNIC',
    regex: '^\\d{13}$',
  },
  {
    country: 'Panama',
    countryCode: 'PA',
    flag: '🇵🇦',
    taxIdName: 'RUC',
    regex: '^\\d{9}$',
  },
  {
    country: 'Paraguay',
    countryCode: 'PY',
    flag: '🇵🇾',
    taxIdName: 'RUC',
    regex: '^\\d{7,9}$',
  },
  {
    country: 'Peru',
    countryCode: 'PE',
    flag: '🇵🇪',
    taxIdName: 'RUC',
    regex: '^\\d{11}$',
  },
  {
    country: 'Philippines',
    countryCode: 'PH',
    flag: '🇵🇭',
    taxIdName: 'TIN',
    regex: '^\\d{9,12}$',
  },
  {
    country: 'Poland',
    countryCode: 'PL',
    flag: '🇵🇱',
    taxIdName: 'NIP',
    regex: '^\\d{10}$',
  },
  {
    country: 'Portugal',
    countryCode: 'PT',
    flag: '🇵🇹',
    taxIdName: 'NIF',
    regex: '^\\d{9}$',
  },
  { country: 'Qatar', countryCode: 'QA', flag: '🇶🇦', taxIdName: '', regex: '' },
  {
    country: 'Romania',
    countryCode: 'RO',
    flag: '🇷🇴',
    taxIdName: 'CUI',
    regex: '^\\d{9}$',
  },
  {
    country: 'Russia',
    countryCode: 'RU',
    flag: '🇷🇺',
    taxIdName: 'INN',
    regex: '^\\d{10}$|^\\d{12}$',
  },
  {
    country: 'Saudi Arabia',
    countryCode: 'SA',
    flag: '🇸🇦',
    taxIdName: 'Tax ID / Iqama',
    regex: '^\\d{10}$',
  },
  {
    country: 'Singapore',
    countryCode: 'SG',
    flag: '🇸🇬',
    taxIdName: 'NRIC',
    regex: '^[STFG]\\d{7}[A-Z]$',
  },
  {
    country: 'Slovakia',
    countryCode: 'SK',
    flag: '🇸🇰',
    taxIdName: 'IČ DPH / DIČ',
    regex: '^SK\\d{10}$',
  },
  {
    country: 'Slovenia',
    countryCode: 'SI',
    flag: '🇸🇮',
    taxIdName: 'ID / VAT',
    regex: '^SI\\d{8}$',
  },
  {
    country: 'South Africa',
    countryCode: 'ZA',
    flag: '🇿🇦',
    taxIdName: 'ID',
    regex: '^\\d{13}$',
  },
  {
    country: 'South Korea',
    countryCode: 'KR',
    flag: '🇰🇷',
    taxIdName: 'Business Registration No.',
    regex: '^\\d{10}$',
  },
  {
    country: 'Spain',
    countryCode: 'ES',
    flag: '🇪🇸',
    taxIdName: 'NIF/NIE',
    regex: '^[A-Z0-9]\\d{7}[A-Z0-9]$',
  },
  {
    country: 'Sri Lanka',
    countryCode: 'LK',
    flag: '🇱🇰',
    taxIdName: 'TIN',
    regex: '^\\d{9}$',
  },
  {
    country: 'Sudan',
    countryCode: 'SD',
    flag: '🇸🇩',
    taxIdName: 'TIN',
    regex: '^\\d{10}$',
  },
  {
    country: 'Sweden',
    countryCode: 'SE',
    flag: '🇸🇪',
    taxIdName: 'Personnummer',
    regex: '^\\d{6}[-]?\\d{4}$',
  },
  {
    country: 'Switzerland',
    countryCode: 'CH',
    flag: '🇨🇭',
    taxIdName: 'UID',
    regex: '^CHE\\d{9}$',
  },
  {
    country: 'Taiwan',
    countryCode: 'TW',
    flag: '🇹🇼',
    taxIdName: 'Uniform ID',
    regex: '^[A-Z]\\d{9}$',
  },
  {
    country: 'Thailand',
    countryCode: 'TH',
    flag: '🇹🇭',
    taxIdName: 'Citizen ID',
    regex: '^\\d{13}$',
  },
  {
    country: 'Tunisia',
    countryCode: 'TN',
    flag: '🇹🇳',
    taxIdName: 'Identifiant Fiscal',
    regex: '^\\d{8}$',
  },
  {
    country: 'Turkey',
    countryCode: 'TR',
    flag: '🇹🇷',
    taxIdName: 'T.C. Kimlik No',
    regex: '^\\d{11}$',
  },
  {
    country: 'Ukraine',
    countryCode: 'UA',
    flag: '🇺🇦',
    taxIdName: 'Tax ID',
    regex: '^\\d{10,12}$',
  },
  {
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    taxIdName: 'NINO',
    regex: '^[A-CEGHJ-PR-TW-Z]{2}\\d{6}[A-D]$',
  },
  {
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    taxIdName: 'UTR',
    regex: '^\\d{10}$',
  },
  {
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    taxIdName: 'SSN',
    regex: '^\\d{3}-\\d{2}-\\d{4}$',
  },
  {
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    taxIdName: 'EIN',
    regex: '^\\d{2}-\\d{7}$',
  },
  {
    country: 'Uruguay',
    countryCode: 'UY',
    flag: '🇺🇾',
    taxIdName: 'RUC / TIN',
    regex: '^\\d{12}$',
  },
  {
    country: 'Vietnam',
    countryCode: 'VN',
    flag: '🇻🇳',
    taxIdName: 'MST',
    regex: '^\\d{10,13}$',
  },
  {
    country: 'Zimbabwe',
    countryCode: 'ZW',
    flag: '🇿🇼',
    taxIdName: 'TIN',
    regex: '^\\d{10}$',
  },
];
